version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

init:

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  # COMPlus_UseManagedHttpClientHandler: false
  CERTES_ACME_ACCOUNT_KEY:
    secure: fmkn8cbE+A1dHITS3s7NADqKi+2rYNKSSjuuLWvkX199WThoEptlCXKAwxlMhWZtBrXdNU5D+1RHI2ouDwWF7hwcIHcGf30v2UohFR+YHujT/N6c4EnK3261CNNm6AklbINPJ72+QPu04/NqEzDAtA==
  CERTES_AZURE_SUBSCRIPTION_ID:
    secure: FSK01SfyZI0x6AX2XVDxcE6kUAmg4fYja2hsNcQNBxa1PBddSZtZ8rthvO5c8o/R
  CERTES_AZURE_TENANT_ID:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  CERTES_AZURE_CLIENT_ID:
    secure: icfPnryDWgqU1TmP3J7gsidrpY9jGAuWY4gXf6CeDkVOELNN25JaeMvaRztUqtlb
  CERTES_AZURE_CLIENT_SECRET:
    secure: igTLkiccsMP8ctXsHH6ymG8CKv6dXbi0HUqjcqyjfAZcgJp5NtDWH/7Ch0FVw9gt

cache:
#  - dotnet-pre

install:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -InstallDir ./dotnet-pre -Version 2.1.300-preview2-008530 -NoPath
  - ps: >-
        If ($env:APPVEYOR_SCHEDULED_BUILD -eq "True") {
            $domain = "*.lo0.in";
            $pkgInfo = wget "https://api-v2v3search-1.nuget.org/query?q=dotnet-certes&prerelease=true" | ConvertFrom-Json
            $latestVer = $pkgInfo.data.versions | Select-Object -Last 1
            wget "https://www.nuget.org/api/v2/package/Certes/$($latestVer.version)" -outfile "dotnet-certes.$($latestVer.version).nupkg"
        } Else {
            $domain = "*.$($env:APPVEYOR_BUILD_NUMBER).lo0.in";
            $pkgInfo = wget "https://www.myget.org/F/certes/api/v3/query?q=dotnet-certes&prerelease=true" | ConvertFrom-Json
            $latestVer = $pkgInfo.data.versions | where {$_.version -like "*-master-*"} | Select-Object -Last 1
            wget "https://www.myget.org/F/certes/api/v2/package/dotnet-certes/$($latestVer.version)" -outfile "dotnet-certes.$($latestVer.version).nupkg"
        }
  - ps: $latestVer = $pkgInfo.data.versions | where {$_.version -like "*-master-*"} | Select-Object -Last 1
  - ps: ./dotnet-pre/dotnet.exe tool install dotnet-certes -g --configfile .\NuGet.config --version $($latestVer.version)
  - ps: $env:DOTNET_ROOT = "$($env:APPVEYOR_BUILD_FOLDER)\dotnet-pre"
  - ps: $env:Path += ";$($env:USERPROFILE)\.dotnet\tools\"

nuget:
  disable_publish_on_pr: true

build_script:
  # create wildcard order
  - ps: Add-AppveyorMessage -Message "certes order new $domain"
  - ps: $order = certes order new $domain | ConvertFrom-Json
  - ps: $orderLocation = $order.location
  - ps: Add-AppveyorMessage -Message $orderLocation
  # deploy DNS response to Azure
  - ps: Add-AppveyorMessage -Message "certes az dns $orderLocation $domain --resource-group certes"
  - ps: certes az dns $orderLocation $domain --resource-group certes | Out-Null
  # validate DNS response
  - ps: Add-AppveyorMessage -Message "certes order validate $orderLocation $domain dns"
  - ps: certes order validate $orderLocation $domain dns | Out-Null
  # submit CSR
  - ps: Add-AppveyorMessage -Message "certes order finalize $orderLocation --dn `"CN=$($domain)`" --out ./key.pem"
  - ps: certes order finalize $orderLocation --dn "CN=$($domain)" --out ./key.pem | Out-Null
  # install SSL binding for Azure web app
#  - ps: certes az app $orderLocation www.lo0.in certes --slot ci --resource-group certes --private-key ./key.pem
  # export certificate
  - ps: Add-AppveyorMessage -Message "certes cert pem $orderLocation --out cert.pem"
  - ps: certes cert pem $orderLocation --out cert.pem | Out-Null
  - ps: Add-AppveyorMessage -Message "certes cert pfx $orderLocation certes --private-key ./key.pem --out cert.pfx"
  - ps: certes cert pfx $orderLocation certes --private-key ./key.pem --out cert.pfx | Out-Null

test: off

artifacts:
  - path: '**\*.pfx'
    name: pfx

  - path: '**\*.pem'
    name: pem

deploy:
  - provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    description: 'PFX password: certes'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: pfx,pem
    draft: false
    prerelease: false
    on:
      branch: master
