version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

init:

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  ACME_DIR: https://acme-staging-v02.api.letsencrypt.org/directory
  CERTES_ACME_ACCOUNT_KEY:
    secure: fmkn8cbE+A1dHITS3s7NADqKi+2rYNKSSjuuLWvkX18GrFJggVJlvBRLrvyGddusgPP6ZpGcwo2xnBy1qmPkX4zfRGcHy5zXME79iCMbABqSgsuXTR9mbNI1yij/NthMN+VLYJj9/50oroAtJ9cSIA==
  CERTES_AZURE_SUBSCRIPTION_ID:
    secure: FSK01SfyZI0x6AX2XVDxcE6kUAmg4fYja2hsNcQNBxa1PBddSZtZ8rthvO5c8o/R
  CERTES_AZURE_TALENT_ID:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  CERTES_AZURE_CLIENT_ID:
    secure: icfPnryDWgqU1TmP3J7gsidrpY9jGAuWY4gXf6CeDkVOELNN25JaeMvaRztUqtlb
  CERTES_AZURE_CLIENT_SECRET:
    secure: igTLkiccsMP8ctXsHH6ymG8CKv6dXbi0HUqjcqyjfAZcgJp5NtDWH/7Ch0FVw9gt

cache:
  - dotnet-pre

install:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300-preview1-008174 -InstallDir ./dotnet-pre -NoPath
  - ps: ./dotnet-pre/dotnet.exe install tool dotnet-certes --version 1.0.0-master-780 --source https://www.myget.org/F/certes/api/v3/index.json -g
  - ps: new-alias certes "$env:USERPROFILE\.dotnet\tools\certes.exe"

nuget:
  disable_publish_on_pr: true

build_script:
  # create wildcard order
  - ps: $order = certes order new *.lo0.in --server $env:ACME_DIR | ConvertFrom-Json
  - ps: Add-AppveyorMessage -Message $order.location
  # deploy DNS response to Azure
  - ps: certes az dns $order.location *.lo0.in --resource-group certes | Out-Null
  # validate DNS response
  - ps: certes order validate $order.location *.lo0.in dns --server $env:ACME_DIR | Out-Null
  # submit CSR
  - ps: certes order finalize $order.location --dn "CN=*.lo0.in" --out ./key.pem --server $env:ACME_DIR | Out-Null
  # export certificate
  - ps: certes cert pem $order.location --out cert.pem --server $env:ACME_DIR | Out-Null
  - ps: certes cert pfx $order.location certes --private-key ./key.pem --out cert.pfx --server $env:ACME_DIR | Out-Null

test: off

artifacts:
  - path: '**\*.pfx'
  - path: '**\*.pem'
