version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

init:

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  ACME_DIR: https://acme-staging-v02.api.letsencrypt.org/directory
  CERTES_ACME_ACCOUNT_KEY:
    secure: fmkn8cbE+A1dHITS3s7NADqKi+2rYNKSSjuuLWvkX1/9hLRkhO9VZMOsE0kVgvXUJUPt6Q604QxQwQ7w6jxvW6W7q0SRUcsnFjp7b6UfN5zmBZXcUnxBPbU1rbXUuVO7RX5G6j9H6WRQNeiYVtsfbw==
    
cache:
  - dotnet-pre

install:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -InstallDir ./dotnet-pre -Version 2.1.300-preview1-008174 -NoPath
  - ps: ./dotnet-pre/dotnet.exe install tool dotnet-certes --version 1.0.0-master-776 --source https://www.myget.org/F/certes/api/v3/index.json -g

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: certes order new *.lo0.in --server $env:SRV

artifacts:
  - path: '**\*.pfx'
  - path: '**\*.pem'
