version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

init:

skip_tags: true

image: Visual Studio 2017
shallow_clone: true
clone_depth: 1

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 0
  CERTES_ACME_ACCOUNT_KEY:
    secure: fmkn8cbE+A1dHITS3s7NADqKi+2rYNKSSjuuLWvkX199WThoEptlCXKAwxlMhWZtBrXdNU5D+1RHI2ouDwWF7hwcIHcGf30v2UohFR+YHujT/N6c4EnK3261CNNm6AklbINPJ72+QPu04/NqEzDAtA==
  CERTES_AZURE_SUBSCRIPTION_ID:
    secure: FSK01SfyZI0x6AX2XVDxcE6kUAmg4fYja2hsNcQNBxa1PBddSZtZ8rthvO5c8o/R
  CERTES_AZURE_TENANT_ID:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  CERTES_AZURE_CLIENT_ID:
    secure: icfPnryDWgqU1TmP3J7gsidrpY9jGAuWY4gXf6CeDkVOELNN25JaeMvaRztUqtlb
  CERTES_AZURE_CLIENT_SECRET:
    secure: igTLkiccsMP8ctXsHH6ymG8CKv6dXbi0HUqjcqyjfAZcgJp5NtDWH/7Ch0FVw9gt

cache:
  - dotnet-pre

install:
  - ps: wget https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -InstallDir ./dotnet-pre -Version 2.1.300-preview2-008530 -NoPath
  - ps: ./dotnet-pre/dotnet.exe tool install dotnet-certes -g --version 1.0.1-preview-871
  - ps: $env:DOTNET_ROOT = "$($env:APPVEYOR_BUILD_FOLDER)\dotnet-pre"
  - ps: $env:Path += ";$($env:USERPROFILE)\.dotnet\tools\"

nuget:
  disable_publish_on_pr: true

build_script:
  # create wildcard order
  - ps: $order = certes order new *.lo0.in | ConvertFrom-Json
  - ps: Add-AppveyorMessage -Message $order.location
  # deploy DNS response to Azure
  - ps: certes az dns $order.location *.lo0.in --resource-group certes | Out-Null
  # validate DNS response
  - ps: certes order validate $order.location *.lo0.in dns | Out-Null
  # submit CSR
  - ps: certes order finalize $order.location --dn "CN=*.lo0.in" --out ./key.pem | Out-Null
  # install SSL binding for Azure web app
  - ps: certes az app $order.location www.lo0.in certes --slot ci --resource-group certes --private-key ./key.pem | Out-Null
  # export certificate
  - ps: certes cert pem $order.location --out cert.pem | Out-Null
  - ps: certes cert pfx $order.location certes --private-key ./key.pem --out cert.pfx | Out-Null

test: off

artifacts:
  - path: '**\*.pfx'
    name: pfx

  - path: '**\*.pem'
    name: pem

deploy:
  - provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    description: 'PFX password: certes'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: pfx,pem
    draft: false
    prerelease: false
    on:
      branch: master
